### ISSUE TITLE
Windows 1.7 version - unexpected header

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ColinPitrat/kalenji-gps-watch-reader#22] opened 2015-03-13 21:56 UTC
```
steps to reproduce:

* Running zadig
** Options list all devices
** stm32 virtual com port -> winusb install driver
* run kalenji_reader -d . -o tcx

Output:
Using device type Kalenji 500 or 700: GH-675
Unexpected header for getList: 16
Unexpected size in header for getList: ♫ (!= 116 - 4)
Size is not a multiple of 24 in getList !


```

Original issue reported on code.google.com by `steven.leeman` on 4 May 2014 at 3:44

**Comment by ColinPitrat** [comment] 2015-08-29 15:41
Considering this issue as a duplicate of issue 15.
Do not hesitate to reopen or open a new one if you manage to reproduce with more debug info.

**Closed by ColinPitrat** 2015-08-29 15:41 UTC
